#!/usr/bin/python3

result = False
equation = input('Введите простое уравнение: ')

if '+' in equation:
    result = int(equation[:equation.index('+')]) + int(equation[equation.index('+') + 1:])
elif '-' in equation:
    result = int(equation[:equation.index('-')]) - int(equation[equation.index('-') + 1:])
elif '*' in equation:
    result = int(equation[:equation.index('*')]) * int(equation[equation.index('*') + 1:])
elif '/' in equation:
    if int(equation[equation.index('/') + 1:]) != 0:
        result = int(equation[:equation.index('/')]) / int(equation[equation.index('/') + 1:])
    else:
        print("Нельзя делить на ноль.")

if result == False:
    print('Ошибочное уравнение.')
else:
    print(f"Результат: {result}.")